//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospudka.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hospudka.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Binary {
            get {
                object obj = ResourceManager.GetObject("Binary", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ButtonAll {
            get {
                return ResourceManager.GetString("ButtonAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clos&amp;e.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string ButtonIgnore {
            get {
                return ResourceManager.GetString("ButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No to All.
        /// </summary>
        internal static string ButtonNoAll {
            get {
                return ResourceManager.GetString("ButtonNoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes to All.
        /// </summary>
        internal static string ButtonYesAll {
            get {
                return ResourceManager.GetString("ButtonYesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string CaptionAbout {
            get {
                return ResourceManager.GetString("CaptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPS.
        /// </summary>
        internal static string CaptionCapsLock {
            get {
                return ResourceManager.GetString("CaptionCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Remote Configuration File.
        /// </summary>
        internal static string CaptionEditRemoteConfig {
            get {
                return ResourceManager.GetString("CaptionEditRemoteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder / Decoder.
        /// </summary>
        internal static string CaptionEncoderDecoder {
            get {
                return ResourceManager.GetString("CaptionEncoderDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string CaptionExport {
            get {
                return ResourceManager.GetString("CaptionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string CaptionFind {
            get {
                return ResourceManager.GetString("CaptionFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        internal static string CaptionInsert {
            get {
                return ResourceManager.GetString("CaptionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUM.
        /// </summary>
        internal static string CaptionNumLock {
            get {
                return ResourceManager.GetString("CaptionNumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVR.
        /// </summary>
        internal static string CaptionOverWrite {
            get {
                return ResourceManager.GetString("CaptionOverWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Output.
        /// </summary>
        internal static string CaptionPrintOutput {
            get {
                return ResourceManager.GetString("CaptionPrintOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string CaptionQuestion {
            get {
                return ResourceManager.GetString("CaptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCRL.
        /// </summary>
        internal static string CaptionScrollLock {
            get {
                return ResourceManager.GetString("CaptionScrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check.
        /// </summary>
        internal static string CaptionUpdateCheck {
            get {
                return ResourceManager.GetString("CaptionUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Config {
            get {
                object obj = ResourceManager.GetObject("Config", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospudka deploy tool..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Find {
            get {
                object obj = ResourceManager.GetObject("Find", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gong {
            get {
                object obj = ResourceManager.GetObject("Gong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrýt menu.
        /// </summary>
        internal static string HtmlContentHideMenu {
            get {
                return ResourceManager.GetString("HtmlContentHideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit menu.
        /// </summary>
        internal static string HtmlContentShowMenu {
            get {
                return ResourceManager.GetString("HtmlContentShowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available version:.
        /// </summary>
        internal static string LabelAvailableVersion {
            get {
                return ResourceManager.GetString("LabelAvailableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version:.
        /// </summary>
        internal static string LabelCurrentVersion {
            get {
                return ResourceManager.GetString("LabelCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target framework:.
        /// </summary>
        internal static string LabelTargetFramework {
            get {
                return ResourceManager.GetString("LabelTargetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string LabelWebsite {
            get {
                return ResourceManager.GetString("LabelWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on &amp;Top.
        /// </summary>
        internal static string MenuItemAlwaysOnTop {
            get {
                return ResourceManager.GetString("MenuItemAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analy&amp;ze URL....
        /// </summary>
        internal static string MenuItemAnalyzeUrl {
            get {
                return ResourceManager.GetString("MenuItemAnalyzeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Alphanu&amp;meric ASCII Only.
        /// </summary>
        internal static string MenuItemASCIIAlphanumeric {
            get {
                return ResourceManager.GetString("MenuItemASCIIAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To All Possible Pri&amp;ntable ASCII.
        /// </summary>
        internal static string MenuItemASCIIFull {
            get {
                return ResourceManager.GetString("MenuItemASCIIFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To &amp;Safe File Name ASCII.
        /// </summary>
        internal static string MenuItemASCIISafeFileName {
            get {
                return ResourceManager.GetString("MenuItemASCIISafeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Safe Pat&amp;h ASCII.
        /// </summary>
        internal static string MenuItemASCIISafePath {
            get {
                return ResourceManager.GetString("MenuItemASCIISafePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for &amp;Updates....
        /// </summary>
        internal static string MenuItemCheckForUpdates {
            get {
                return ResourceManager.GetString("MenuItemCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clea&amp;r Input.
        /// </summary>
        internal static string MenuItemClearInput {
            get {
                return ResourceManager.GetString("MenuItemClearInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cle&amp;ar Output.
        /// </summary>
        internal static string MenuItemClearOutput {
            get {
                return ResourceManager.GetString("MenuItemClearOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string MenuItemCopy {
            get {
                return ResourceManager.GetString("MenuItemCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &amp;About Text.
        /// </summary>
        internal static string MenuItemCopyAbout {
            get {
                return ResourceManager.GetString("MenuItemCopyAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy Text.
        /// </summary>
        internal static string MenuItemCopyText {
            get {
                return ResourceManager.GetString("MenuItemCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy URL.
        /// </summary>
        internal static string MenuItemCopyUrl {
            get {
                return ResourceManager.GetString("MenuItemCopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy Version.
        /// </summary>
        internal static string MenuItemCopyVersion {
            get {
                return ResourceManager.GetString("MenuItemCopyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string MenuItemCut {
            get {
                return ResourceManager.GetString("MenuItemCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode &amp;Base64 to UTF-8.
        /// </summary>
        internal static string MenuItemDecodeBase64 {
            get {
                return ResourceManager.GetString("MenuItemDecodeBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;ecode URL.
        /// </summary>
        internal static string MenuItemDecodeUrl {
            get {
                return ResourceManager.GetString("MenuItemDecodeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string MenuItemDelete {
            get {
                return ResourceManager.GetString("MenuItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode UTF-8 to Base&amp;64.
        /// </summary>
        internal static string MenuItemEncodeBase64 {
            get {
                return ResourceManager.GetString("MenuItemEncodeBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enco&amp;der / Decoder....
        /// </summary>
        internal static string MenuItemEncoderDecoder {
            get {
                return ResourceManager.GetString("MenuItemEncoderDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode According to RFC &amp;1738.
        /// </summary>
        internal static string MenuItemEncodeRFC1738 {
            get {
                return ResourceManager.GetString("MenuItemEncodeRFC1738", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode According to RFC &amp;3986.
        /// </summary>
        internal static string MenuItemEncodeRFC3986 {
            get {
                return ResourceManager.GetString("MenuItemEncodeRFC3986", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export....
        /// </summary>
        internal static string MenuItemExport {
            get {
                return ResourceManager.GetString("MenuItemExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find....
        /// </summary>
        internal static string MenuItemFind {
            get {
                return ResourceManager.GetString("MenuItemFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fi&amp;nd Next.
        /// </summary>
        internal static string MenuItemFindNext {
            get {
                return ResourceManager.GetString("MenuItemFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Flip.
        /// </summary>
        internal static string MenuItemFlip {
            get {
                return ResourceManager.GetString("MenuItemFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus &amp;Input.
        /// </summary>
        internal static string MenuItemFocusInput {
            get {
                return ResourceManager.GetString("MenuItemFocusInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus &amp;Output.
        /// </summary>
        internal static string MenuItemFocusOutput {
            get {
                return ResourceManager.GetString("MenuItemFocusOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&amp;aunch Calculator.
        /// </summary>
        internal static string MenuItemLaunchCalculator {
            get {
                return ResourceManager.GetString("MenuItemLaunchCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Character &amp;Map.
        /// </summary>
        internal static string MenuItemLaunchCharMap {
            get {
                return ResourceManager.GetString("MenuItemLaunchCharMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lau&amp;nch Notepad.
        /// </summary>
        internal static string MenuItemLaunchNotepad {
            get {
                return ResourceManager.GetString("MenuItemLaunchNotepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch &amp;WordPad.
        /// </summary>
        internal static string MenuItemLaunchWordPad {
            get {
                return ResourceManager.GetString("MenuItemLaunchWordPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online &amp;Help.
        /// </summary>
        internal static string MenuItemOnlineHelp {
            get {
                return ResourceManager.GetString("MenuItemOnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open in Default Browser....
        /// </summary>
        internal static string MenuItemOpenInDefaultBrowser {
            get {
                return ResourceManager.GetString("MenuItemOpenInDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string MenuItemOptions {
            get {
                return ResourceManager.GetString("MenuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse UR&amp;L.
        /// </summary>
        internal static string MenuItemParseUrl {
            get {
                return ResourceManager.GetString("MenuItemParseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string MenuItemPaste {
            get {
                return ResourceManager.GetString("MenuItemPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print....
        /// </summary>
        internal static string MenuItemPrint {
            get {
                return ResourceManager.GetString("MenuItemPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print I&amp;mage....
        /// </summary>
        internal static string MenuItemPrintImage {
            get {
                return ResourceManager.GetString("MenuItemPrintImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pri&amp;nt Image Preview....
        /// </summary>
        internal static string MenuItemPrintImagePreview {
            get {
                return ResourceManager.GetString("MenuItemPrintImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pre&amp;view....
        /// </summary>
        internal static string MenuItemPrintPreview {
            get {
                return ResourceManager.GetString("MenuItemPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string MenuItemSave {
            get {
                return ResourceManager.GetString("MenuItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string MenuItemSelectAll {
            get {
                return ResourceManager.GetString("MenuItemSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MenuItemTools {
            get {
                return ResourceManager.GetString("MenuItemTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu&amp;rn off the Monitors....
        /// </summary>
        internal static string MenuItemTurnOffMonitors {
            get {
                return ResourceManager.GetString("MenuItemTurnOffMonitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string MenuItemUndo {
            get {
                return ResourceManager.GetString("MenuItemUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Word Wrap.
        /// </summary>
        internal static string MenuItemWordWrap {
            get {
                return ResourceManager.GetString("MenuItemWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applicacion cannot run on your system..
        /// </summary>
        internal static string MessageApplicationCannotRun {
            get {
                return ResourceManager.GetString("MessageApplicationCannotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured. Application will close now..
        /// </summary>
        internal static string MessageApplicationError {
            get {
                return ResourceManager.GetString("MessageApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Config hash cannot be empty..
        /// </summary>
        internal static string MessageConfigHashEmptyError {
            get {
                return ResourceManager.GetString("MessageConfigHashEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string MessageConnecting {
            get {
                return ResourceManager.GetString("MessageConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected text has been copied to clipboard..
        /// </summary>
        internal static string MessageCopiedToClipboard {
            get {
                return ResourceManager.GetString("MessageCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting files....
        /// </summary>
        internal static string MessageCountingFiles {
            get {
                return ResourceManager.GetString("MessageCountingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating directory: {0}....
        /// </summary>
        internal static string MessageCreatingDirectory {
            get {
                return ResourceManager.GetString("MessageCreatingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file: {0}....
        /// </summary>
        internal static string MessageDeletingFile {
            get {
                return ResourceManager.GetString("MessageDeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string MessageDone {
            get {
                return ResourceManager.GetString("MessageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed.
        /// </summary>
        internal static string MessageExportFailed {
            get {
                return ResourceManager.GetString("MessageExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export finished.
        /// </summary>
        internal static string MessageExportFinished {
            get {
                return ResourceManager.GetString("MessageExportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string MessageExporting {
            get {
                return ResourceManager.GetString("MessageExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating preview....
        /// </summary>
        internal static string MessageGeneratingPreview {
            get {
                return ResourceManager.GetString("MessageGeneratingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid hash..
        /// </summary>
        internal static string MessageInvalidHashError {
            get {
                return ResourceManager.GetString("MessageInvalidHashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageInvalidResponse.
        /// </summary>
        internal static string MessageInvalidResponse {
            get {
                return ResourceManager.GetString("MessageInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing hash..
        /// </summary>
        internal static string MessageMissingHashError {
            get {
                return ResourceManager.GetString("MessageMissingHashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to do.
        /// </summary>
        internal static string MessageNothingToDo {
            get {
                return ResourceManager.GetString("MessageNothingToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Out of memory..
        /// </summary>
        internal static string MessageOutOfMemoryError {
            get {
                return ResourceManager.GetString("MessageOutOfMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching....
        /// </summary>
        internal static string MessagePatching {
            get {
                return ResourceManager.GetString("MessagePatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences saved.
        /// </summary>
        internal static string MessagePreferencesSaved {
            get {
                return ResourceManager.GetString("MessagePreferencesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview generated.
        /// </summary>
        internal static string MessagePreviewGenerated {
            get {
                return ResourceManager.GetString("MessagePreviewGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing....
        /// </summary>
        internal static string MessagePrinting {
            get {
                return ResourceManager.GetString("MessagePrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing failed.
        /// </summary>
        internal static string MessagePrintingFailed {
            get {
                return ResourceManager.GetString("MessagePrintingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing finished.
        /// </summary>
        internal static string MessagePrintingFinished {
            get {
                return ResourceManager.GetString("MessagePrintingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the current print operation?.
        /// </summary>
        internal static string MessageQuestionCancelPrinting {
            get {
                return ResourceManager.GetString("MessageQuestionCancelPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MessageReady {
            get {
                return ResourceManager.GetString("MessageReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing directory: {0}....
        /// </summary>
        internal static string MessageRemovingDirectory {
            get {
                return ResourceManager.GetString("MessageRemovingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the remote configuration file?.
        /// </summary>
        internal static string MessageSaveChanges {
            get {
                return ResourceManager.GetString("MessageSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string MessageSaved {
            get {
                return ResourceManager.GetString("MessageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string MessageSaving {
            get {
                return ResourceManager.GetString("MessageSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Saving failed.
        /// </summary>
        internal static string MessageSavingFailed {
            get {
                return ResourceManager.GetString("MessageSavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available..
        /// </summary>
        internal static string MessageUpdateAvailable {
            get {
                return ResourceManager.GetString("MessageUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates. Please try again later..
        /// </summary>
        internal static string MessageUpdateCheckError {
            get {
                return ResourceManager.GetString("MessageUpdateCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file: {0}....
        /// </summary>
        internal static string MessageUploadingFile {
            get {
                return ResourceManager.GetString("MessageUploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is up to date..
        /// </summary>
        internal static string MessageUpToDate {
            get {
                return ResourceManager.GetString("MessageUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldError {
            get {
                object obj = ResourceManager.GetObject("ShieldError", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldOK {
            get {
                object obj = ResourceManager.GetObject("ShieldOK", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldQuestion {
            get {
                object obj = ResourceManager.GetObject("ShieldQuestion", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldQuestionRed {
            get {
                object obj = ResourceManager.GetObject("ShieldQuestionRed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldWarning {
            get {
                object obj = ResourceManager.GetObject("ShieldWarning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit website.
        /// </summary>
        internal static string ToolTipVisit {
            get {
                return ResourceManager.GetString("ToolTipVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fortsoft.eu/.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
